## lec29 データのマージ

In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame

In [2]:
dframe1 = DataFrame({'key':['X','Z','Y','Z','X','X'],'data_set_1': np.arange(6)})
dframe1

key  data_set_1
0   X           0
1   Z           1
2   Y           2
3   Z           3
4   X           4
5   X           5

In [4]:
dframe2 = DataFrame({'key':['Q','Y','Z'],'data_set_2': [1 ,2,3]})
dframe2

key  data_set_2
0   Q           1
1   Y           2
2   Z           3

In [5]:
pd.merge(dframe1, dframe2)

key  data_set_1  data_set_2
0   Z           1           3
1   Z           3           3
2   Y           2           2

In [7]:
pd.merge(dframe1, dframe2, on='key')

key  data_set_1  data_set_2
0   Z           1           3
1   Z           3           3
2   Y           2           2

In [8]:
pd.merge(dframe1, dframe2, on='key', how ='left')

key  data_set_1  data_set_2
0   X           0         NaN
1   Z           1         3.0
2   Y           2         2.0
3   Z           3         3.0
4   X           4         NaN
5   X           5         NaN

## lec30 データの連結

In [9]:
# DataFrameを2つ用意
df_left = DataFrame({'key': ['X','Y','Z','X','Y'],
                  'data': range(5)})
df_right = DataFrame({'group_data': [10, 20]}, index=['X', 'Y'])

In [10]:
df_left

key  data
0   X     0
1   Y     1
2   Z     2
3   X     3
4   Y     4

In [11]:
df_right

group_data
X          10
Y          20

In [14]:
pd.merge(df_left,df_right, left_on='key', right_index=True)

key  data  group_data
0   X     0          10
3   X     3          10
1   Y     1          20
4   Y     4          20

In [17]:
pd.merge(df_left,df_right, left_on='key', right_index=True, how = 'outer')

key  data  group_data
0   X     0        10.0
3   X     3        10.0
1   Y     1        20.0
4   Y     4        20.0
2   Z     2         NaN

In [18]:
# 階層的なindexの場合
df_left_hr = DataFrame({'key1': ['SF','SF','SF','LA','LA'],
                   'key2': [10, 20, 30, 20, 30],
                   'data_set': np.arange(5.)})
df_right_hr = DataFrame(np.arange(10).reshape((5, 2)),
                   index=[['LA','LA','SF','SF','SF'],
                          [20, 10, 10, 10, 20]],
                   columns=['col_1', 'col_2'])

In [19]:
df_left_hr

key1  key2  data_set
0   SF    10       0.0
1   SF    20       1.0
2   SF    30       2.0
3   LA    20       3.0
4   LA    30       4.0

In [20]:
df_right_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [21]:
pd.merge(df_left_hr, df_right_hr, left_on=['key1', 'key2'], right_index=True)

key1  key2  data_set  col_1  col_2
0   SF    10       0.0      4      5
0   SF    10       0.0      6      7
1   SF    20       1.0      8      9
3   LA    20       3.0      0      1

## データの連結

In [22]:
arr1 = np.arange(9).reshape((3,3))

In [23]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
# 行方向に連結
np.concatenate([arr1, arr1], axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [25]:
# 列方向に連結
np.concatenate([arr1, arr1], axis = 0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
# pandas
from pandas import Series, DataFrame
# pandas.Series
ser1 =  Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])
# concatで、デフォルトは axis=0
pd.concat([ser1,ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [28]:
ser1

T    0
U    1
V    2
dtype: int64

In [29]:
ser2

X    3
Y    4
dtype: int64

In [30]:
# DataFrame
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

In [31]:
dframe1

X         Y         Z
0  0.459596 -0.189663 -0.638951
1 -0.641298 -0.821244  0.707427
2  1.200247 -0.026807 -0.924105
3 -0.029425  0.252255  0.000965

In [32]:
dframe2

Y         Q         X
0  0.866138  0.312569 -0.490562
1 -1.027657  0.873068 -1.567173
2  0.520242 -0.629084 -0.324543

In [33]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0  0.459596 -0.189663 -0.638951       NaN
1 -0.641298 -0.821244  0.707427       NaN
2  1.200247 -0.026807 -0.924105       NaN
3 -0.029425  0.252255  0.000965       NaN
0 -0.490562  0.866138       NaN  0.312569
1 -1.567173 -1.027657       NaN  0.873068
2 -0.324543  0.520242       NaN -0.629084

In [35]:
# 元のデータフレームのインデックスを無視してマージする
pd.concat([dframe1,dframe2],ignore_index=True )

X         Y         Z         Q
0  0.459596 -0.189663 -0.638951       NaN
1 -0.641298 -0.821244  0.707427       NaN
2  1.200247 -0.026807 -0.924105       NaN
3 -0.029425  0.252255  0.000965       NaN
4 -0.490562  0.866138       NaN  0.312569
5 -1.567173 -1.027657       NaN  0.873068
6 -0.324543  0.520242       NaN -0.629084

## lec 33 データを組み合わせる

In [1]:

import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
# いくつかサンプルになるデータを作ります。
ser1 = Series([2,np.nan,4,np.nan,6,np.nan],
           index=['Q','R','S','T','U','V'])

# 長さを同じにします。
ser2 = Series(np.arange(len(ser1), dtype=np.float64),
           index=['Q','R','S','T','U','V'])

In [3]:
ser1

Q    2.0
R    NaN
S    4.0
T    NaN
U    6.0
V    NaN
dtype: float64

In [4]:
ser2

Q    0.0
R    1.0
S    2.0
T    3.0
U    4.0
V    5.0
dtype: float64

In [9]:
np.where(pd.isnull(ser1))

(array([1, 3, 5], dtype=int64),)

In [10]:
Series(np.where(pd.isnull(ser1),ser2, ser1),index=ser1.index)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [11]:
ser1.combine_first(ser2)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [13]:
dframe_odds = DataFrame({'X': [1., np.nan, 3., np.nan],
                     'Y': [np.nan, 5., np.nan, 7.],
                     'Z': [np.nan, 9., np.nan, 11.]})
dframe_evens = DataFrame({'X': [2., 4., np.nan, 6., 8.],
                     'Y': [np.nan, 10., 12., 14., 16.]})

In [14]:
dframe_odds

X    Y     Z
0  1.0  NaN   NaN
1  NaN  5.0   9.0
2  3.0  NaN   NaN
3  NaN  7.0  11.0

In [15]:
dframe_evens

X     Y
0  2.0   NaN
1  4.0  10.0
2  NaN  12.0
3  6.0  14.0
4  8.0  16.0

In [16]:
dframe_odds.combine_first(dframe_evens)

X     Y     Z
0  1.0   NaN   NaN
1  4.0   5.0   9.0
2  3.0  12.0   NaN
3  6.0   7.0  11.0
4  8.0  16.0   NaN

## lec33 SeriesとDateFrameの変換

In [17]:
dframe1 = DataFrame(np.arange(8).reshape((2, 4)),
                 index=pd.Index(['LA', 'SF'], name='city'),
                 columns=pd.Index(['A', 'B', 'C','D'], name='letter'))
dframe1

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [20]:
dframe_st = dframe1.stack()
dframe_st

city  letter
LA    A         0
      B         1
      C         2
      D         3
SF    A         4
      B         5
      C         6
      D         7
dtype: int32

In [21]:
dframe_st.unstack()

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [22]:
dframe_st.unstack(0)

city    LA  SF
letter        
A        0   4
B        1   5
C        2   6
D        3   7

In [25]:
dframe_st.unstack('letter')

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [27]:
dframe_st.unstack('city')

city    LA  SF
letter        
A        0   4
B        1   5
C        2   6
D        3   7

## ピボットテーブル

In [29]:
import pandas.util.testing as tm
tm.N = 3

# ちょっとした関数を作ります。
def unpivot(frame):
    N, K = frame.shape
    data = {'value' : frame.values.ravel('F'),
            'variable' : np.asarray(frame.columns).repeat(N),
            'date' : np.tile(np.asarray(frame.index), K)}
    return DataFrame(data, columns=['date', 'variable', 'value'])

# DataFrameを作ります。
dframe = unpivot(tm.makeTimeDataFrame())
dframe

C:\Users\yuji\AppData\Local\Temp\ipykernel_20152\2793324504.py:1: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


date variable     value
0   2000-01-03        A -0.220708
1   2000-01-04        A  0.639396
2   2000-01-05        A  0.477246
3   2000-01-06        A -1.175015
4   2000-01-07        A  0.637996
..         ...      ...       ...
115 2000-02-07        D -0.690183
116 2000-02-08        D -0.459064
117 2000-02-09        D  0.679095
118 2000-02-10        D  0.117644
119 2000-02-11        D -1.529707

[120 rows x 3 columns]

In [30]:
dfram_piv = dframe.pivot('date', 'variable', 'value')

In [31]:
dfram_piv

variable           A         B         C         D
date                                              
2000-01-03 -0.220708 -0.624329  0.471118  0.490245
2000-01-04  0.639396 -0.846788  0.821092 -0.368718
2000-01-05  0.477246  1.387672 -0.912656  0.780035
2000-01-06 -1.175015 -1.922870 -0.530043  1.744969
2000-01-07  0.637996 -0.533244 -0.473802  0.806449
2000-01-10 -0.303918  1.266535  0.723870 -0.724886
2000-01-11 -1.212842  1.203524  1.312867  1.867707
2000-01-12  1.732212 -1.033043  0.546735  0.578075
2000-01-13 -1.109774  0.283203  0.877179 -0.098446
2000-01-14 -2.428099  0.928598 -0.709692 -0.089909
2000-01-17  0.812871  0.119281  0.764517 -0.024468
2000-01-18  1.529123 -1.076475 -0.096827 -0.664308
2000-01-19 -1.088504  0.341831  1.202667 -1.438622
2000-01-20  0.302084 -0.162160 -0.384577  0.325681
2000-01-21  0.896883 -0.042559  0.037630 -0.969741
2000-01-24 -0.294761  0.041280  0.872759  0.856174
2000-01-25  0.578973  0.220059  0.115822 -0.412079
2000-01-26 -1.120860  0.475919 -0.757264 -2.438127
2000-01-27 -0.391671  0.198829  0.621890  0.027009
2000-01-28 -0.704518  0.230039 -0.797512 -0.342159
2000-01-31 -0.453213  0.908409  1.448970  0.203244
2000-02-01  0.949503  1.008703  3.099287 -0.016391
2000-02-02 -0.118073 -1.371966  1.493280  0.349106
2000-02-03 -2.291156 -0.499914  1.515753  1.384168
2000-02-04  2.522341 -0.616141  0.980333 -0.497840
2000-02-07  1.024659 -0.670357  1.522134 -0.690183
2000-02-08 -1.446810 -0.386476  1.375124 -0.459064
2000-02-09  1.511237 -0.548795 -1.075229  0.679095
2000-02-10 -1.740354 -0.695839 -0.655652  0.117644
2000-02-11 -0.033596 -0.819550  0.088407 -1.529707

## 重複したデータの処理

In [32]:
dframe = DataFrame({'key1': ['A'] * 2 + ['B'] * 3,
                  'key2': [2, 2, 2, 3, 3]})
dframe

key1  key2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [33]:
dframe.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [34]:
dframe.drop_duplicates()

key1  key2
0    A     2
2    B     2
3    B     3

In [35]:
dframe.drop_duplicates(['key1'])

key1  key2
0    A     2
2    B     2

## lec36

In [37]:
dframe = DataFrame({'city':['Alma','Brian Head','Fox Park'],
                    'altitude':[3158,3000,2762]})
dframe

city  altitude
0        Alma      3158
1  Brian Head      3000
2    Fox Park      2762

In [42]:
state_map={'Alma':'Colorado','Brian Head':'Utah','Fox Park':'Wyoming'}

In [43]:
dframe['state'] = dframe['city'].map(state_map)
dframe

city  altitude     state
0        Alma      3158  Colorado
1  Brian Head      3000      Utah
2    Fox Park      2762   Wyoming

In [45]:
dframe['key1'] = [0,1,2]
dframe

city  altitude     state  key1
0        Alma      3158  Colorado     0
1  Brian Head      3000      Utah     1
2    Fox Park      2762   Wyoming     2

## 37 置換

In [47]:
ser1 = Series([1,2,3,4,1,2,3,4])

In [48]:
ser1

0    1
1    2
2    3
3    4
4    1
5    2
6    3
7    4
dtype: int64

In [49]:
ser1.replace(1, np.nan)

0    NaN
1    2.0
2    3.0
3    4.0
4    NaN
5    2.0
6    3.0
7    4.0
dtype: float64

In [50]:
# 複数同時置換
ser1.replace([1,4], [100,400])

0    100
1      2
2      3
3    400
4    100
5      2
6      3
7    400
dtype: int64

In [51]:
# 辞書を渡す
ser1.replace({4:np.nan})

0    1.0
1    2.0
2    3.0
3    NaN
4    1.0
5    2.0
6    3.0
7    NaN
dtype: float64

# 38 indexの変更

In [53]:
dframe = DataFrame(np.arange(12).reshape((3,4)),
                   index = ['NY', 'LA', 'SF'],
                   columns = {'A','B','C','D'})
dframe

C  A   D   B
NY  0  1   2   3
LA  4  5   6   7
SF  8  9  10  11

In [54]:
str.lower('A')

'a'

In [55]:
dframe.index.map(str.lower)

Index(['ny', 'la', 'sf'], dtype='object')

In [57]:
str.title('udemyis good')

'Udemyis Good'

In [58]:
dframe.rename(index= str.title, columns = str.lower)

c  a   d   b
Ny  0  1   2   3
La  4  5   6   7
Sf  8  9  10  11

In [62]:
dframe.rename(index={'ny': 'NEW YORK'}, columns = {'A':'ALPHA'}, inplace = True)
dframe

C  ALPHA   D   B
NY  0      1   2   3
LA  4      5   6   7
SF  8      9  10  11

## ビニング

In [63]:

years = [1990,1991,1992,2008,2012,2015,1987,1969,2013,2008,1999]

In [64]:
len(years)

11

In [65]:
decade_bins = [1960,1970,1980,1990,2000,2010,2020]

In [69]:
decade_cat = pd.cut(years,decade_bins)

In [71]:
decade_cat

[(1980, 1990], (1990, 2000], (1990, 2000], (2000, 2010], (2010, 2020], ..., (1980, 1990], (1960, 1970], (2010, 2020], (2000, 2010], (1990, 2000]]
Length: 11
Categories (6, interval[int64, right]): [(1960, 1970] < (1970, 1980] < (1980, 1990] < (1990, 2000] < (2000, 2010] < (2010, 2020]]

In [72]:
decade_cat.categories

IntervalIndex([(1960, 1970], (1970, 1980], (1980, 1990], (1990, 2000], (2000, 2010], (2010, 2020]], dtype='interval[int64, right]')

In [73]:
pd.value_counts(decade_cat)

(1990, 2000]    3
(2010, 2020]    3
(1980, 1990]    2
(2000, 2010]    2
(1960, 1970]    1
(1970, 1980]    0
dtype: int64

In [74]:
pd.cut(years, 2)

[(1968.954, 1992.0], (1968.954, 1992.0], (1968.954, 1992.0], (1992.0, 2015.0], (1992.0, 2015.0], ..., (1968.954, 1992.0], (1968.954, 1992.0], (1992.0, 2015.0], (1992.0, 2015.0], (1992.0, 2015.0]]
Length: 11
Categories (2, interval[float64, right]): [(1968.954, 1992.0] < (1992.0, 2015.0]]

## 40 外れ値

In [79]:
# 乱数列の種を与えます。
np.random.seed(12345)
dframe = DataFrame(np.random.randn(1000,4))
dframe

0         1         2         3
0   -0.204708  0.478943 -0.519439 -0.555730
1    1.965781  1.393406  0.092908  0.281746
2    0.769023  1.246435  1.007189 -1.296221
3    0.274992  0.228913  1.352917  0.886429
4   -2.001637 -0.371843  1.669025 -0.438570
..        ...       ...       ...       ...
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

[1000 rows x 4 columns]

In [83]:
np.random.seed(1234)
dframe2 = DataFrame(np.random.randn(1000,4))
dframe2

0         1         2         3
0    0.471435 -1.190976  1.432707 -0.312652
1   -0.720589  0.887163  0.859588 -0.636524
2    0.015696 -2.242685  1.150036  0.991946
3    0.953324 -2.021255 -0.334077  0.002118
4    0.405453  0.289092  1.321158 -1.546906
..        ...       ...       ...       ...
995  0.606620  1.446567 -0.691402  0.955149
996  0.672142 -0.355116 -0.240102  0.232473
997  0.525020 -0.012250 -0.484403  0.761125
998 -0.307001 -0.215848 -0.750894  0.283353
999 -0.120901  0.702997 -0.318599  0.232615

[1000 rows x 4 columns]

In [84]:
dframe.tail()

0         1         2         3
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

In [85]:
dframe.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [88]:
col = dframe[0]
col

0     -0.204708
1      1.965781
2      0.769023
3      0.274992
4     -2.001637
         ...   
995    1.089085
996   -0.478509
997   -1.946267
998   -1.293122
999    0.089987
Name: 0, Length: 1000, dtype: float64

In [89]:
col.head()

0   -0.204708
1    1.965781
2    0.769023
3    0.274992
4   -2.001637
Name: 0, dtype: float64

In [90]:
col[np.abs(col)>3]

523   -3.428254
900    3.366626
Name: 0, dtype: float64

In [93]:
dframe[(np.abs(dframe)>3).any(1)]

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

In [94]:
# sign プラスなら1.0,, マイナスなら-1.0が返るメソッド
np.sign(dframe)

0    1    2    3
0   -1.0  1.0 -1.0 -1.0
1    1.0  1.0  1.0  1.0
2    1.0  1.0  1.0 -1.0
3    1.0  1.0  1.0  1.0
4   -1.0 -1.0  1.0 -1.0
..   ...  ...  ...  ...
995  1.0  1.0 -1.0  1.0
996 -1.0 -1.0 -1.0 -1.0
997 -1.0  1.0  1.0  1.0
998 -1.0 -1.0 -1.0 -1.0
999  1.0  1.0  1.0  1.0

[1000 rows x 4 columns]

In [95]:
dframe[np.abs(dframe)>3] = np.sign(dframe)*3

In [96]:
dframe

0         1         2         3
0   -0.204708  0.478943 -0.519439 -0.555730
1    1.965781  1.393406  0.092908  0.281746
2    0.769023  1.246435  1.007189 -1.296221
3    0.274992  0.228913  1.352917  0.886429
4   -2.001637 -0.371843  1.669025 -0.438570
..        ...       ...       ...       ...
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

[1000 rows x 4 columns]

## 41 permutation

In [100]:
dframe = DataFrame(np.arange(4 * 4).reshape((4, 4)))
# 0,1,2,3をpermutateしたarrayを取得します。

dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [103]:
blender = np.array([0,3,2,1,])
dframe.take(blender)

0   1   2   3
0   0   1   2   3
3  12  13  14  15
2   8   9  10  11
1   4   5   6   7

In [105]:
blender = np.random.permutation(4)
blender

array([3, 1, 2, 0])

In [106]:
# 箱の中に、A,B,C というラベルの付いたビー玉があるとします。
box = np.array(['A','B','C'])
# ランダムにビー玉を取り出す操作を10回やってみましょう。
shaker = np.random.randint(0, len(box), size=10)

In [107]:
shaker

array([0, 1, 1, 0, 0, 1, 1, 1, 2, 2])

In [108]:
hands_grabs = box.take(shaker)

In [109]:
hands_grabs

array(['A', 'B', 'B', 'A', 'A', 'B', 'B', 'B', 'C', 'C'], dtype='<U1')